### ISSUE TITLE
Err(Other(ClientImport("Runtime Ethereum block not found, rejecting!")))

### ISSUE THREAD

**Issue by kamiloski88** [digitalnativeinc/standard-substrate#113]
Version: 0.9.12-3
OS: Ubuntu 20.04
I have run my new validator and in status I get errors (Err(Other(ClientImport("Runtime Ethereum block not found, rejecting!")))

Steps:
1. Login to server
2. pulls latest release tag **(0.9.12-3)** and sets it as var - LATEST_RELEASE=`curl --silent "https://api.github.com/repos/digitalnativeinc/standard-substrate/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'`
3. downloads binary based on latest tag set - wget -O opportunity-standalone https://github.com/digitalnativeinc/standard-substrate/releases/download/$LATEST_RELEASE/opportunity-standalone-linux-x86_64
4. chmod +x ./opportunity-standalone
5. mv opportunity-standalone /usr/local/bin
6. touch /etc/systemd/system/opportunity-standalone.service
7.  paste content into the file
# copy everything line 12-28 inclusive
cat > /etc/systemd/system/opportunity-standalone.service << EOF
[Unit]
Description=Standard Validator

[Service]
ExecStart=/usr/local/bin/opportunity-standalone \
--base-path <data-dir> \
--chain opportunity \
--port 30333 \
--name <node-name> \
--validator
Restart=always
RestartSec=120

[Install]
WantedBy=multi-user.target
EOF
8.systemctl daemon-reload
9. systemctl enable opportunity-standalone
10. systemctl start opportunity-standalone
11. systemctl status opportunity-standalone

Results:
Errors in console:

Dec 24 22:41:07 Standard opportunity-standalone[5435]: 2021-12-24 22:41:07 💤 Idle (0 peers), best: #0 (0x0250…4bce), finalized #0 (0x0250…4bce), ⬇ 5.4kiB/s ⬆ 6.1kiB/s
Dec 24 22:41:12 Standard opportunity-standalone[5435]: 2021-12-24 22:41:12 💤 Idle (0 peers), best: #0 (0x0250…4bce), finalized #0 (0x0250…4bce), ⬇ 0.5kiB/s ⬆ 0.9kiB/s
Dec 24 22:41:13 Standard opportunity-standalone[5435]: 2021-12-24 22:41:13 💔 Error importing block 0x22ac8aa3bd4844da1a0d1b5dca6e98f00ebea5080153686d0ef7be2b74dc228d: Err(Other(ClientImport("Runtime Ethereum block not found, rejecting!")))
Dec 24 22:41:13 Standard opportunity-standalone[5435]: 2021-12-24 22:41:13 💔 Error importing block 0x22ac8aa3bd4844da1a0d1b5dca6e98f00ebea5080153686d0ef7be2b74dc228d: Err(Other(ClientImport("Runtime Ethereum block not found, rejecting!")))

**Comment by koburzasty** [comment]
I have the same error with version 0.9.12-3.

**Comment by firke** [comment]
@kamiloski88 @koburzasty This has been fixed in the latest release - 0.9.12-4, try purging/deleting the local database and syncing it, should be all working. Thanks! Once confirmed will close it.

**Comment by koburzasty** [comment]
@firke Yesterday I downloaded the source and compiled it - it worked.
Today, after returning home, I will check the new release.

**Comment by kamiloski88** [comment]
Fixed with version 0.9.12-4
